### ISSUE TITLE
List of contributors missing once API rate limit exceeded (message needed)

### ISSUE THREAD

**Issue by vanguard07** [publiclab/community-toolbox#53] opened 2018-10-03 20:32 UTC
![screenshot 87](https://user-images.githubusercontent.com/23207859/46437632-72746100-c779-11e8-907c-a118dfdaf8c3.png)

Maybe the API limit has exceeded, please look into it.

**Comment by Rishabh570** [comment] 2018-10-04 02:36
There is a limit of 5000 requests per hour for **authenticated** requests from a user on Github API. I don't think that could be the reason here...

**Comment by Rishabh570** [comment] 2018-10-04 05:10
Oh, it just happened with me also, actually we're sending unauthenticated requests to Github API, which has hourly limit of 60 (much less than authenticated request's limit), that's the cause of this behaviour...

To fix this we can pass `Authorization header` in the request `getRepoContributors` inside `community-toolbox.js`...but for that, we need user-session token.

@jywarren @sagarpreet-chadha Can I make this a **fto issue**? (Newcomer would have to just put the header in the request with session-token provided by me)

**Comment by Rishabh570** [comment] 2018-10-07 16:48
Actually, adding auth header won't be a fix for this issue for *two reasons*:
- For auth header, we need to put, personal auth token of someone's Github account in the code, which obviously doesn't sound a good idea
- Second, if we do that anyways, we need to periodically change the auth token because it expires after a week or two...which leads to reduntant commits in the history

A better way would be to store the result in **localStorage** so that we don't need to fetch it with every page reload.

I would like to work on it :)

**Comment by jywarren** [comment] 2018-10-10 00:13
> For auth header, we need to put, personal auth token of someone's Github account in the code, which obviously doesn't sound a good idea

Yes, this is why it's based around an unauthenticated request... this also sort of "shares" the load across all users rather than piles them up on a single user.

I like the localStorage solution -- moving to #61 and renaming this to be more specific!

But I think we can also have a second solution -- to show a `GitHub API limit exceeded` message, for now (Great first-timer issue!) when it fails, and then later when we have localstorage, `GitHub API limit exceeded; cached results shown.`

How does this sound? Would we now have to catch the error in the Promise @Rishabh570 ?

Thank you all for finding and describing this so carefully! 👍 


```
Failed to load resource: the server responded with a status of 403 (Forbidden)
:8000/#r=all:1 Uncaught (in promise) StatusCodeErrorerror: {message: "API rate limit exceeded for 113.110.231.235. (But …t. Check out the documentation for more details.)", documentation_url: "https://developer.github.com/v3/#rate-limiting"}message: "403 - [object Object]"name: "StatusCodeError"options: {baseUrl: "https://api.github.com", headers: {…}, json: true, method: "GET", qs: {…}, …}response: exports.IncomingMessage {_readableState: ReadableState, readable: false, _events: {…}, _eventsCount: 4, _maxListeners: undefined, …}statusCode: 403isOperational: truestack: "StatusCodeError: 403 - [object Object]↵    at new StatusCodeError (http://localhost:8000/dist/community-toolbox.js:63719:15)↵    at Request.RP$callback [as _callback] (http://localhost:8000/dist/community-toolbox.js:63800:32)↵    at Request.self.callback (http://localhost:8000/dist/community-toolbox.js:65543:22)↵    at emitTwo (http://localhost:8000/dist/community-toolbox.js:31148:13)↵    at Request.emit (http://localhost:8000/dist/community-toolbox.js:31219:7)↵    at Request.<anonymous> (http://localhost:8000/dist/community-toolbox.js:66519:10)↵    at emitOne (http://localhost:8000/dist/community-toolbox.js:31138:13)↵    at Request.emit (http://localhost:8000/dist/community-toolbox.js:31216:7)↵    at exports.IncomingMessage.<anonymous> (http://localhost:8000/dist/community-toolbox.js:66441:12)↵    at Object.onceWrapper (http://localhost:8000/dist/community-toolbox.js:31319:30)↵    at emitNone (http://localhost:8000/dist/community-toolbox.js:31133:20)↵    at exports.IncomingMessage.emit (http://localhost:8000/dist/community-toolbox.js:31213:7)↵    at endReadableNT (http://localhost:8000/dist/community-toolbox.js:62592:12)↵    at afterTickTwo (http://localhost:8000/dist/community-toolbox.js:59159:10)↵    at Item.run (http://localhost:8000/dist/community-toolbox.js:59332:14)↵    at drainQueue (http://localhost:8000/dist/community-toolbox.js:59302:42)"__proto__: Error
```

**Comment by jywarren** [comment] 2018-10-10 00:14
Could we catch the `message` field in the status code error object as cited above? What line of code would we catch that error on, for matching the string `API rate limit exceeded for xxx.xxx.xxx.xxx` ...

**Comment by Rishabh570** [comment] 2018-10-10 03:38
> But I think we can also have a second solution -- to show a GitHub API limit exceeded message, for now (Great first-timer issue!) when it fails, and then later when we have localstorage, GitHub API limit exceeded; cached results shown.

@jywarren Sounds great! but how do we show that messages of API limit exceeded or not :thinking: an alert box(that fades after 1sec or so) or something else?

**Comment by jywarren** [comment] 2018-10-10 03:41
Sure, we could even show just a <p> with a notice. Thanks!

**Comment by Rishabh570** [comment] 2018-10-10 03:42
Yep, we have to put catch blocks in places where network calls happening...but I observed that the error object doesn't contain `API limit exceeded for ...`, it only has a status of `403`, so we can put a simple statement checking if the `error.status == 403` and if its true, we can call some function from `ui.js` to show the appropriate message to the user...

**Comment by Rishabh570** [comment] 2018-10-10 03:46
![screenshot from 2018-10-10 09-15-44](https://user-images.githubusercontent.com/25483260/46712124-2d669800-cc6d-11e8-94b0-a3256d58bdbb.png)

This is the error object that I'm getting...

**Closed** 2018-10-10 09:33 UTC
