### ISSUE TITLE
Contributors list is empty - error?

### ISSUE THREAD

**Issue by jywarren** [publiclab/community-toolbox#112] opened 2019-01-02 22:50 UTC
Hmm, at https://code.publiclab.org#r=all, i'm seeing nobody in the contributors list; same in incognito mode. I haven't loaded it for days, so I don't think it's queue exhaustion. Anyone have ideas? @Rishabh570 maybe?

Thanks!

![screenshot 2019-01-02 at 5 35 57 pm](https://user-images.githubusercontent.com/24359/50616555-e75d5100-0eb6-11e9-93f6-ecea02516c03.png)

**Comment by Rishabh570** [comment] 2019-01-03 07:21
Hmm, I've also tried it on `code.publiclab.org` and it turns out that it's hitting the quota limit and hence not being able to show every piece of info that is required...
For some quick maths, 
- Recent contributors part eats up 20 requests (10 for monthly and 10 for weekly) and its optimization is WIP, we'll able to reduce it to 10 requests in total...
- All contributors list (as shown on `code.publiclab.org#r=all`) eats up 20 requests
- Repo contributors list (which currently shows only for a single repo) eats up only 1 request
- Finally, fetching the list of top repos takes 1 request.

So, according to that, we're well under `60`, I wonder how it's hitting the limit...
@jywarren I doubt it could be due to the recent PR merged which included changes in `dist/` file...I'll revert to previous commits and see if this problem persists...

**Comment by Rishabh570** [comment] 2019-01-03 15:39
@jywarren I tested after going back in commits (recent ones) and it's working properly at that point...I believe 2 of the recent commits (which include changes in `dist/`) are the cause, let me just be sure enough then I'll update you!

**Comment by jywarren** [comment] 2019-01-03 17:21
also we may not be on a very recent version in gh-pages, so perhaps we
should start versioning more consistently -- you should be able to check
package.json at least though...

**Comment by subhahu123** [comment] 2019-01-06 18:13
![screenshot from 2019-01-06 23-41-46](https://user-images.githubusercontent.com/34541684/50739936-bfe6eb00-120c-11e9-89ca-64d6629ca0e4.png)

github api server is showing 403 error
@jywarren  @Rishabh570

**Comment by subhahu123** [comment] 2019-01-06 18:15
it's showing that 

{
  "message": "API rate limit exceeded for 139.167.207.65. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
![screenshot from 2019-01-06 23-44-46](https://user-images.githubusercontent.com/34541684/50739953-148a6600-120d-11e9-8298-6f8bff48f719.png)

**Comment by subhahu123** [comment] 2019-01-06 18:19
i don't think that this is because of last commits
it is about api rate list exceding

**Comment by jywarren** [comment] 2019-01-07 15:34
Hmm. Here's what i see in logs:

https://gist.github.com/jywarren/d1e74c754a52cc51db709f7c4d0a13f7

It still looks like the 403 exhausted queue. How long should it take for my queue to refill?

```
/#r=all:1 Uncaught (in promise) StatusCodeError {name: "StatusCodeError", statusCode: 403, message: "403 - [object Object]", error: {…}, options: {…}, …}
```

**Comment by jywarren** [comment] 2019-01-07 15:34
Anyways glad most people aren't seeing this!

**Comment by Rishabh570** [comment] 2019-01-07 15:39
After every 60min queue gets refilled...
Can you please try once again when your quota get refilled (takes 1hr to refill), just remove everything from your localStorage and then visit the site (make sure to visit the URL after removing the localStorage)...if it still throws 403, something wrong is in the code then...

**Comment by jywarren** [comment] 2019-01-07 15:41
ok!

**Comment by Rishabh570** [comment] 2019-01-08 11:37
@jywarren One more thing, can we just remove these two commits from main, [this](https://github.com/publiclab/community-toolbox/commit/5ab07cda0a9effdad9caf48d41412dbbf69b660a) and [this](https://github.com/publiclab/community-toolbox/commit/7ef2324e091d10e04a24098244fdd731a0ecd75c) as these contain changes in `dist/`?

As an aside, `gh-pages` would be suitable for testing my changes I guess..?

**Comment by Rishabh570** [comment] 2019-01-10 15:09
@jywarren I've found why we're hitting the limits of API almost everytime :smile: 
Actually, we're making 2 requests per repository...first to collect total number of pages that the request gives us back and then iterating on those pages to collect the data of contributors...so we're making ~40 requests for 20 repos and 20 is consumed by the data of recent contributors and some extra requests for fetching repos and issues. Hence, we're going above 60.

I'll be refactoring the code now...Mainly the focus will be,
- Reducing the requests per repo so that we make ~20 requests for 20 repos (we might sacrifice preciseness of contributors count, the biggest difference will occur in `plots2` contributors' data because its response contains 4 pages of data & we'll be getting data from only 1 page if we want to reduce the requests count...it would be a tradeoff)...[_suggestion needed_]

- Reducing the number of requests we make for showing `recent contributors`. Currently, code makes 10 requests for fetching contributors last week and 10 for contributors last month...I'll try to do all this with 10 requests for contributors last month and filtering out contributors last week out of them.

And, after above things get done...there'll be 1 remaining thing to which is, showing recent contribs and normal contribs according to repository filter provided in the URL...but this will be covered in my "MVC" PR...

**Comment by jywarren** [comment] 2019-01-10 22:35
wow this is super awesome work!!! Thank you so much!

Hmm. Could we... get more complete data for fewer repositories? Like 4
pages from the top 10, or top 8?

**Comment by Rishabh570** [comment] 2019-01-11 07:34
Actually, I'm also thinking this way :)
I guess only `plots2` contains 4 pages of data (because it has approx 334 contribs) and other top 19 repos need only 1 page (because they have less than 100 contribs)...

I'll take a look at the contribs count once again for each repo to be sure...I guess we'll able to allow few repos to make more than 1 requests...

**Comment by Rishabh570** [comment] 2019-01-11 17:24
Hi @jywarren, can you please take a look at https://rishabh570.github.io/community-toolbox/
I've done some modifications and pushed them to my `gh-pages` branch and they're live at above URL...can you please visit this and check if everything is working fine or not (hopefully 403 shouldn't be there now)...

**Comment by Rishabh570** [comment] 2019-01-12 02:15
@jywarren Yes, quota should be full...

**Comment by Rishabh570** [comment] 2019-01-12 18:16
@jywarren Is it working fine? I would be opening a PR for it if its working okay... :crossed_fingers:

**Closed** 2019-01-15 02:50 UTC
Labels: bug, help wanted
